# Generated by Django 4.1.1 on 2022-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Clname', models.CharField(max_length=50)),
                ('Cemail', models.CharField(max_length=50)),
                ('Cphone', models.IntegerField(max_length=50)),
                ('Cno_people', models.IntegerField(max_length=50)),
                ('Cenquiry', models.CharField(max_length=250)),
            ],
        ),
    ]
