# Generated by Django 4.1.1 on 2022-09-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodexercise',
            name='Cno_people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodexercise',
            name='Cphone',
            field=models.IntegerField(),
        ),
    ]
